name: Cache System Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run cache tests
      run: npm test -- test/cache
      env:
        NODE_ENV: test
    
    - name: Generate coverage report
      run: npm run test:coverage
    
    - name: Upload coverage to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.node-version }}
        path: coverage/
    
    - name: Check test results
      run: |
        if [ -f coverage/lcov-report/index.html ]; then
          echo "✅ Coverage report generated successfully"
        else
          echo "❌ Coverage report not found"
          exit 1
        fi